# Generated by Django 2.1.7 on 2020-03-02 15:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('bill_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='0', max_length=200)),
                ('media', models.ImageField(blank=True, null=True, upload_to='bookings/')),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='problem_sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('aadhar_number', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('parent_mobile', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=100)),
                ('school_education', models.CharField(max_length=200)),
                ('technical_education', models.CharField(max_length=200)),
                ('technical_education_domain', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lon', models.CharField(blank=True, max_length=100, null=True)),
                ('active_booking', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area', verbose_name='area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_types/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Booking')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProblemSubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ServiceType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='problemsubcategory',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ServiceType'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City', verbose_name='city'),
        ),
    ]
