# Generated by Django 3.0.3 on 2020-03-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_servicelocations'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='lat',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='lon',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceLocations',
        ),
    ]
