# Generated by Django 3.0.3 on 2020-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200301_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='lon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
