# Generated by Django 3.0.3 on 2020-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200301_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='problem_sub_category')),
            ],
        ),
    ]
