# Generated by Django 3.0.3 on 2020-03-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_problemsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsubcategory',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ServiceType'),
            preserve_default=False,
        ),
    ]
