# Generated by Django 3.0.3 on 2020-03-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_problemsubcategory_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Booking')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProblemSubCategory')),
            ],
        ),
    ]
