# Generated by Django 3.0.3 on 2020-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subcategorybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='bookings/'),
        ),
    ]
