# Generated by Django 3.0.3 on 2020-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200301_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='minimum_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
