# Generated by Django 3.0.3 on 2020-03-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_booking_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='active_booking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ServiceProvider'),
        ),
    ]
